from pathlib import Path

path = Path('docs/ROADMAP.md')
text = path.read_text()

replacements = [
    (
        "Stream C continues in parallel on RF-037 through RF-043 plus RF-057/RF-058; simulator use in Stream C is limited to presentation consequences after live security authority is fixed.",
        "Stream C continues in parallel on RF-037 through RF-043 plus RF-057/RF-058; after the live security authority is fixed, simulator-driven multi-client/browser scenarios may exercise that real boundary end-to-end, but security evidence remains owned by the signalling/network authority rather than the simulator."
    ),
    (
        "5. **P1-USIM + AR-7 RF-049 + AR-8 RF-050** belong to the parallel UI convergence/evidence stream: IWER supplies the intermediate simulator tier for applicable spatial/input invariants; physical Quest remains the promotion authority for device-dependent evidence.",
        "5. **P1-USIM + AR-7 RF-049 + AR-8 RF-050** belong to the parallel XR convergence/evidence stream: IWER supplies both interaction evidence and the USIM-A architecture-conformance tier for lifecycle, persistence, reference-space and clean-artifact invariants; physical Quest remains the promotion authority for device-dependent evidence."
    ),
    (
        "| RF-046 | Investigation provenance / digest completeness | High | The SHA-256 investigation digest was cryptographically strong but its v1 preimage was a lossy semantic projection. | **IMPLEMENTATION LANDED / REVIEW ACTIVE:** v2 semantic digest (`sha256-canonical-investigation-v2`) commits per-entity canonical hashes for governed events/results/structures/observations/findings/annotations/representation state/discoveries/NIL/research context, excludes presentation-only/replay-volatile identity deliberately, and has mutation/tamper plus legacy-v1 compatibility coverage. Preserve this contract and complete merged-state review before `VERIFIED COMPLETE`. |",
        "| RF-046 | Investigation provenance / digest completeness | High | The SHA-256 investigation digest was cryptographically strong but its v1 preimage was a lossy semantic projection. | **IMPLEMENTATION LANDED / REVIEW ACTIVE:** v2 semantic digest (`sha256-canonical-investigation-v2`) commits per-entity canonical hashes for governed events/results/structures/observations/findings/annotations/representation state/discoveries/NIL/research context, excludes presentation-only/replay-volatile identity deliberately, and has mutation/tamper plus legacy-v1 compatibility coverage. Preserve this contract and add USIM-A presentation-independence evidence: identical semantic investigations replayed/restored under different XR poses/modalities/panel layouts must retain the same semantic digest. This is continuing conformance evidence, not a cryptographic redesign. |"
    ),
    (
        "| RF-047 | Investigation replay / non-mutating provenance | High | `InvestigationReplayRunner` currently counts `remediation`/`refusal` events as matched without reconstructing them in the replay Atlas ledger, then computes an investigation digest over the reconstructed state. Session round-trip tests do not prove portable clean-room replay of these events. | **IMPLEMENTATION LANDED / REVIEW ACTIVE:** Replay runner now reconstructs every durable non-mutating provenance event (remediation, refusal) in the replay Atlas ledger without re-executing the original action. After authoritative mutating operations are re-executed, the persisted semantic ledger is restored exactly (`evidenceLedger.restore`) preserving event order, payload, and provenance. Added `compareRemediationEvent`/`compareRefusalEvent` verification comparing event order, full payload (requirementPatch, constraintCode, preflight, etc.), and resulting `remediationEventsVerified`/`refusalEventsVerified` counts in `ReplayVerificationResult`. End-to-end tests for combined timelines pass; refusal-only/remediation-only test coverage added via clean-room replay contract tests. Folded into RF-027/RF-030 completion evidence. |",
        "| RF-047 | Investigation replay / non-mutating provenance | High | `InvestigationReplayRunner` currently counts `remediation`/`refusal` events as matched without reconstructing them in the replay Atlas ledger, then computes an investigation digest over the reconstructed state. Session round-trip tests do not prove portable clean-room replay of these events. | **IMPLEMENTATION LANDED / REVIEW ACTIVE:** Replay runner now reconstructs every durable non-mutating provenance event (remediation, refusal) in the replay Atlas ledger without re-executing the original action. After authoritative mutating operations are re-executed, the persisted semantic ledger is restored exactly (`evidenceLedger.restore`) preserving event order, payload, and provenance. Added `compareRemediationEvent`/`compareRefusalEvent` verification comparing event order, full payload (requirementPatch, constraintCode, preflight, etc.), and resulting `remediationEventsVerified`/`refusalEventsVerified` counts in `ReplayVerificationResult`. End-to-end tests for combined timelines pass; refusal-only/remediation-only test coverage added via clean-room replay contract tests. Add USIM-A cross-pose/cross-modality clean-room replay as product-path evidence that XR presentation state cannot alter semantic reconstruction. |"
    ),
    (
        "| RF-053 | P1-W / production WASM deployment | **Blocker for preview / RE-VERIFY** | The 26 August audit found the generated WASM package absent from the published topology, but current `main@22ce66b` now runs `npm run wasm` before Vite and the active `wasmServePlugin` copies `wasm/pkg` into `dist/wasm/pkg`. The old missing-copy finding is therefore stale; deployment correctness is still unverified until the clean production artifact is exercised at the exact runtime URLs. | Re-run the production-wiring falsifier against a clean build/preview/Netlify-equivalent artifact. Verify JS glue + `.wasm` presence, exact `/wasm/pkg/...` URLs, MIME/hash/manifest expectations, kernel initialization and one authoritative analytical operation with no JS substitute. If those pass, close or narrow RF-053 rather than preserving the superseded defect claim; retain any concrete remaining deployment failure as the new finding. |",
        "| RF-053 | P1-W / production WASM deployment | **Blocker for preview / RE-VERIFY** | The 26 August audit found the generated WASM package absent from the published topology, but current `main@22ce66b` now runs `npm run wasm` before Vite and the active `wasmServePlugin` copies `wasm/pkg` into `dist/wasm/pkg`. The old missing-copy finding is therefore stale; deployment correctness is still unverified until the clean production artifact is exercised at the exact runtime URLs. | Re-run the production-wiring falsifier against a clean build/preview/Netlify-equivalent artifact. Verify JS glue + `.wasm` presence, exact `/wasm/pkg/...` URLs, MIME/hash/manifest expectations, kernel initialization and one authoritative analytical operation with no JS substitute. USIM-A then adds a clean-`dist` immersive WebXR smoke through real Worker + real WASM + visible spatial result/export; this is pre-deployment conformance, not proof of deployed services or Quest performance. If those pass, close or narrow RF-053 rather than preserving the superseded defect claim. |"
    ),
    (
        "- [ ] **PERF-05 / medium:** profile allocations/GC and sustained analytical scheduling across representative interactions, including RF-051 JS preprocessing/transfer.",
        "- [ ] **PERF-05 / medium:** profile allocations/GC and sustained analytical scheduling across representative interactions, including RF-051 JS preprocessing/transfer; add USIM-A repeated XR enter/exit/load/save/restore lifecycle so listener/object/Worker/heap growth is measured as leak evidence, while absolute device budgets remain PERF-04/Quest evidence."
    ),
]

for old, new in replacements:
    if old not in text:
        raise SystemExit(f'missing roadmap anchor: {old[:90]}')
    text = text.replace(old, new, 1)

anchor = "- [ ] fail unsupported simulator capabilities explicitly rather than fabricating success.\n\n**USIM-1 — reference interaction scenarios**"
insert = """- [ ] fail unsupported simulator capabilities explicitly rather than fabricating success.\n\n**USIM-A — architecture conformance pack**\n\nPurpose: use deterministic XR fault injection to attack cross-layer invariants that ordinary unit mocks can miss, without allowing XR presentation state to become a second analytical or persistence authority.\n\n- [ ] **XR lifecycle / async race:** enter XR -> begin real async analysis -> input source disappears or session visibility changes -> exit XR -> analysis completes -> re-enter XR; assert Atlas/Worker generation and output identity remain authoritative, stale captures/listeners do not survive the old session, and presentation recovery cannot duplicate or discard a committed analysis;\n- [ ] **presentation-independent reproducibility:** replay/save/restore the same investigation under standing/controller, seated/hand and varied head/panel poses; assert semantic replay outcome, canonical dataset identity and RF-046 investigation digest are unchanged while presentation state is allowed to differ;\n- [ ] **reference-space integrity:** exercise `local-floor`, seated/standing height, recenter/reset-view and locomotion changes; assert viewer/reference-space transforms cannot mutate durable evidence/annotation/Memory-Palace coordinates unless an explicit governed semantic spatial action occurs;\n- [ ] **resource lifecycle balance:** run repeated enter/exit/load/representation-change/save/restore cycles and assert bounded listeners, interactables, updatables, panels, renderer objects, Worker instances and JS-heap trend; treat this as PERF-05 leak/lifecycle evidence, never as Quest frame-rate or memory qualification;\n- [ ] **clean-production immersive boot:** serve only a clean `dist` artifact, enter simulated immersive WebXR, initialize the real module Worker and real WASM kernel, execute one authoritative operation, produce a visible spatial result and export/replay it; use this as RF-053/RF-056 pre-deployment conformance evidence while preserving deployed-service and physical-device gates;\n- [ ] **Moneta presentation independence:** for identical dataset/evidence/governed requirements, vary head pose, handedness, input modality, panel visibility and desktop-vs-XR entry; representation decisions must remain invariant unless a device/display capability is an explicit governed requirement recorded in provenance.\n\n**USIM-1 — reference interaction scenarios**"""
if anchor not in text:
    raise SystemExit('missing USIM-0 anchor')
text = text.replace(anchor, insert, 1)

anchor = """- [ ] U8 seated/standing, handedness, large-text/high-contrast/reduced-motion, reach/FOV/occlusion adversaries.\n\n**Exit gate:**"""
insert = """- [ ] U8 seated/standing, handedness, large-text/high-contrast/reduced-motion, reach/FOV/occlusion adversaries.\n\n**USIM-C — collaboration conformance, gated by Stream C authority fixes**\n\n- [ ] only after RF-037/RF-038/RF-057 authoritative fixes land, run two or more simulated XR browser clients through the real signalling/WebRTC path to verify spatial presence, pointing, disconnect/reconnect cleanup, stale-pose removal and convergent shared presentation state;\n- [ ] drive an authenticated observer through a forbidden embodied mutation attempt and prove rejection at the real role/security authority; IWER is only the input/client driver and does not itself satisfy the security claim;\n- [ ] pin simulator/runtime versions and record per-client pose/input scripts so collaboration failures are reproducible across builds.\n\n**Exit gate:**"""
if anchor not in text:
    raise SystemExit('missing USIM-2 anchor')
text = text.replace(anchor, insert, 1)

old = "**Exit gate:** one production control is activated via simulated controller and one supported hand path through the real input router; deterministic scenarios emit reproducible measured evidence; disabling simulation restores ordinary browser/native-WebXR behavior; production builds contain no simulator dependency path; simulator limitations are recorded; physical U1/U8/U9/PERF-04 gates remain open."
new = "**Exit gate:** one production control is activated via simulated controller and one supported hand path through the real input router; USIM-A proves lifecycle/persistence/reference-space/clean-artifact invariants through the real browser path; deterministic scenarios emit reproducible measured evidence; disabling simulation restores ordinary browser/native-WebXR behavior; production builds contain no simulator dependency path; simulator limitations are recorded; USIM-C remains gated on real security authority; physical U1/U8/U9/PERF-04 gates remain open."
if old not in text:
    raise SystemExit('missing P1-USIM exit anchor')
text = text.replace(old, new, 1)

old = "Fold deployed-path proof into P1-W1/RF-054. |"
new = "Fold deployed-path proof into P1-W1/RF-054. After these authority fixes land, USIM-C may drive multiple authenticated simulated XR clients through the real path to falsify stale presence, reconnect and role-presentation behavior; simulator success cannot substitute for the security-boundary proof above. |"
if old not in text:
    raise SystemExit('missing RF-057 anchor')
text = text.replace(old, new, 1)

path.write_text(text)
