export { CapabilityFlags, type CapabilityName } from './capabilities.ts';

export {
  KernelUnavailableError,
  KernelAbiError,
  isKernelFatalError,
  getKernelState,
  getRuntimeGeneration,
  getKernelUnavailableReason,
  invalidateRuntime,
  requireRuntime,
  initRuntime,
  isReady,
  capabilities,
  type KernelState,
} from './runtime/RuntimeState.ts';

export {
  refreshMemoryView,
  getMemoryView,
  memory,
  allocBuffer,
  deallocBuffer,
  hostBufferAllocationCount,
  allocBytes,
  deallocBytes,
  readBytes,
  readString,
  readF32,
  readU32,
  update,
  call,
  debugFillPattern,
  commandBufferPtr,
  getCommandBufferBytes,
} from './runtime/MemoryAbi.ts';

export {
  UnsupportedAtScaleError,
  loadCsv,
  loadJson,
  loadTypedColumns,
  loadSample,
  sampleKeys,
  datasetRowCount,
  datasetColumnCount,
  datasetRowView,
  destroyDataset,
  parseDatasetBytes,
  getDatasetJson,
  loadDatasetJson,
  runOperation,
  executeOperation,
  datasetFingerprint,
  inferTopology,
  inferEncodings,
  inferSchema,
  statistics,
  computeSpectralFacts,
  parseArrow,
  computeMapperGraph,
  computePersistenceIntervals,
  computeBetti0Curve,
  computeDatasetStructureProfile,
  tdaResourcePreflight,
  type DatasetRowView,
  type AnalyticalResourceDecision,
  type AnalyticalResourceEstimate,
  type TdaResourcePreflight,
  type TdaExportName,
} from './runtime/DatasetHandleBridge.ts';

export {
  computeRadialTree3d,
  computeGrid3d,
  computeForceDirected3d,
  computeTimeRibbon3d,
  computeGeoSurface3d,
  computeStreamline3d,
} from './runtime/LayoutAbi.ts';

export {
  kernelVersion,
  kernelProvenance,
  solveMoneta,
  solveDraco,
  evaluateMonetaCandidate,
  evaluateDracoCandidate,
  adjustMonetaEvidence,
  adjustDracoEvidence,
  roundTripSemanticEmbodimentPayloadV1,
  compileIntent,
  discoverStructures,
} from './runtime/KernelContractBridge.ts';
