/**
 * ConjecturalProposalV1 — governed speculative/predictive proposal authority (DM-1).
 *
 * Captures hypothesis, imputation, and counterfactual representations generated by
 * System-1, System-2, search, or other predictive models.
 *
 * Invariants:
 * 1. Proposal identity hashes the complete canonical body.
 * 2. Proposal content never enters SemanticSnapshotV1.
 * 3. Property and relation statuses are strictly IMPUTED, HYPOTHESIZED, or COUNTERFACTUAL.
 * 4. Derived-from-conjecture content remains conjectural until an analytical authority independently establishes it.
 *
 * Authority: RFC 0011, A27-1, Full Moneta Completeness Audit 2026-10-04.
 */

import { canonicalSha256Hex } from '../../security/CryptoHash.js';

export const CONJECTURAL_PROPOSAL_SCHEMA_VERSION = 1 as const;

export type ConjecturalEpistemicStatus = 'IMPUTED' | 'HYPOTHESIZED' | 'COUNTERFACTUAL';

export const CONJECTURAL_EPISTEMIC_STATUSES: readonly ConjecturalEpistemicStatus[] = [
  'IMPUTED',
  'HYPOTHESIZED',
  'COUNTERFACTUAL',
] as const;

export interface ConjecturalElementV1 {
  readonly elementId: string;
  readonly kind: string;
  readonly epistemicStatus: ConjecturalEpistemicStatus;
  readonly properties: Readonly<Record<string, unknown>>;
  readonly uncertaintyDisclosure?: string;
  readonly supportingEvidenceReferences?: readonly string[];
  readonly contradictingEvidenceReferences?: readonly string[];
}

export interface ConjecturalRelationV1 {
  readonly relationId: string;
  readonly sourceElementId: string;
  readonly targetElementId: string;
  readonly kind: string;
  readonly epistemicStatus: ConjecturalEpistemicStatus;
  readonly weight?: number;
  readonly rationale?: string;
}

export interface GeneratorProvenanceV1 {
  readonly modelId: string;
  readonly modelVersion: string;
  readonly executionRegime: 'PINNED' | 'ADAPTIVE';
  readonly policyHash?: string;
}

export interface ConjecturalProposalBodyV1 {
  readonly snapshotId: string;
  readonly contextId: string;
  readonly generator: GeneratorProvenanceV1;
  readonly elements: readonly ConjecturalElementV1[];
  readonly relations: readonly ConjecturalRelationV1[];
  readonly assumptions: readonly string[];
  readonly uncertaintyDisclosure: string;
  readonly rationale: string;
}

export interface ConjecturalProposalV1 {
  readonly schemaVersion: typeof CONJECTURAL_PROPOSAL_SCHEMA_VERSION;
  readonly proposalId: string;
  readonly body: ConjecturalProposalBodyV1;
}

export function computeConjecturalProposalId(body: ConjecturalProposalBodyV1): string {
  return `sha256-conjectural-proposal-v1-${canonicalSha256Hex(body)}`;
}

export function createConjecturalProposal(
  input: ConjecturalProposalBodyV1
): ConjecturalProposalV1 {
  // Validate epistemic status of elements
  for (const elem of input.elements) {
    if (!CONJECTURAL_EPISTEMIC_STATUSES.includes(elem.epistemicStatus)) {
      throw new TypeError(
        `[ConjecturalProposal] Invalid element epistemic status: "${elem.epistemicStatus}". Must be one of: ${CONJECTURAL_EPISTEMIC_STATUSES.join(
          ', '
        )}`
      );
    }
  }

  // Validate epistemic status of relations
  for (const rel of input.relations) {
    if (!CONJECTURAL_EPISTEMIC_STATUSES.includes(rel.epistemicStatus)) {
      throw new TypeError(
        `[ConjecturalProposal] Invalid relation epistemic status: "${rel.epistemicStatus}". Must be one of: ${CONJECTURAL_EPISTEMIC_STATUSES.join(
          ', '
        )}`
      );
    }
  }

  const proposalId = computeConjecturalProposalId(input);

  return {
    schemaVersion: CONJECTURAL_PROPOSAL_SCHEMA_VERSION,
    proposalId,
    body: Object.freeze({
      ...input,
      elements: Object.freeze(input.elements.map((e) => Object.freeze({ ...e }))),
      relations: Object.freeze(input.relations.map((r) => Object.freeze({ ...r }))),
      assumptions: Object.freeze([...input.assumptions]),
    }),
  };
}

export function validateConjecturalProposal(candidate: unknown): ConjecturalProposalV1 {
  if (typeof candidate !== 'object' || candidate === null) {
    throw new TypeError('[ConjecturalProposal] Proposal must be a non-null object');
  }
  const c = candidate as Record<string, unknown>;
  if (c.schemaVersion !== CONJECTURAL_PROPOSAL_SCHEMA_VERSION) {
    throw new TypeError(
      `[ConjecturalProposal] Unsupported schema version: ${String(c.schemaVersion)}`
    );
  }
  if (typeof c.proposalId !== 'string' || !c.proposalId.startsWith('sha256-conjectural-proposal-v1-')) {
    throw new TypeError('[ConjecturalProposal] Invalid proposalId prefix');
  }
  if (typeof c.body !== 'object' || c.body === null) {
    throw new TypeError('[ConjecturalProposal] Missing proposal body');
  }

  const body = c.body as ConjecturalProposalBodyV1;
  const expectedId = computeConjecturalProposalId(body);
  if (c.proposalId !== expectedId) {
    throw new Error(
      `[ConjecturalProposal] Proposal identity digest mismatch: claimed ${c.proposalId} vs computed ${expectedId}`
    );
  }

  return candidate as ConjecturalProposalV1;
}
