import type {
  DracoFacts,
  SpectralFacts,
  RepresentationRequirements,
  RepresentationFamily,
} from '../../src/draco/index.ts';
import { createDefaultRequirements } from '../../src/draco/index.ts';

export interface SyntheticFixture {
  name: string;
  description: string;
  facts: DracoFacts;
  spectralFacts?: SpectralFacts | null;
  requirements: RepresentationRequirements;
  expectedFamily: RepresentationFamily;
  minConfidence: number;
}

export const SYNTHETIC_FIXTURES: SyntheticFixture[] = [
  {
    name: 'random-noise',
    description: 'Uniform random point cloud with no clear structure or correlation',
    facts: {
      topology: 'TABULAR',
      rowCount: 100,
      nodeCount: 100,
      edgeCount: 0,
      depth: 0,
      numericColumns: 3,
      categoricalColumns: 0,
      temporalColumns: 0,
      hasTimeSeries: false,
      hasContinuousValues: true,
      density: 0.05,
      estimatedDensity: 0.05,
      outlierCount: 0,
      cardinalityOfColor: 0,
      hasHighCardinality: false,
      isLargeDataset: false,
      clusterCount: 1,
      columnStats: {},
      correlationMatrix: {},
      categoryDistribution: {},
      trendDirection: 'flat',
      seasonalityHint: false,
      hasOutliers: false,
      hasHighVariance: false,
      numericSkew: 0,
      topCategory: null,
    },
    spectralFacts: null,
    requirements: createDefaultRequirements('individual-inspection'),
    expectedFamily: 'POINT',
    minConfidence: 0.5,
  },
  {
    name: 'clustered-data',
    description: 'Multi-modal point distribution with 4 well-separated clusters',
    facts: {
      topology: 'TABULAR',
      rowCount: 300,
      nodeCount: 300,
      edgeCount: 0,
      depth: 0,
      numericColumns: 4,
      categoricalColumns: 1,
      temporalColumns: 0,
      hasTimeSeries: false,
      hasContinuousValues: true,
      density: 0.8,
      estimatedDensity: 0.8,
      outlierCount: 0,
      cardinalityOfColor: 4,
      hasHighCardinality: false,
      isLargeDataset: false,
      clusterCount: 4,
      columnStats: {},
      correlationMatrix: {
        colA: { colB: 0.85, colC: 0.72 },
      },
      categoryDistribution: {},
      trendDirection: 'flat',
      seasonalityHint: false,
      hasOutliers: false,
      hasHighVariance: false,
      numericSkew: 0.2,
      topCategory: null,
    },
    spectralFacts: null,
    requirements: createDefaultRequirements('compare-clusters'),
    expectedFamily: 'CLUSTER',
    minConfidence: 0.55,
  },
  {
    name: 'periodic-signal',
    description: 'Harmonic oscillation with dominant spectral frequency peak',
    facts: {
      topology: 'TIME_SERIES',
      rowCount: 128,
      nodeCount: 128,
      edgeCount: 0,
      depth: 1,
      numericColumns: 1,
      categoricalColumns: 0,
      temporalColumns: 1,
      hasTimeSeries: true,
      hasContinuousValues: true,
      density: 0.1,
      estimatedDensity: 0.1,
      outlierCount: 0,
      cardinalityOfColor: 0,
      hasHighCardinality: false,
      isLargeDataset: false,
      clusterCount: 1,
      columnStats: {},
      correlationMatrix: {},
      categoryDistribution: {},
      trendDirection: 'flat',
      seasonalityHint: true,
      hasOutliers: false,
      hasHighVariance: false,
      numericSkew: 0,
      topCategory: null,
    },
    spectralFacts: {
      dominantFrequencies: [0.0625],
      spectralEntropy: 0.18,
      powerSpectrumPeak: 0.88,
      directionalAnisotropy: 0.0,
      characteristicScale: 16.0,
      hasPeriodicity: true,
      periodicityConfidence: 0.94,
    },
    requirements: createDefaultRequirements('explore'),
    expectedFamily: 'FREQUENCY',
    minConfidence: 0.55,
  },
  {
    name: 'multiscale-anisotropic',
    description: 'Strongly correlated multi-variable clusters',
    facts: {
      topology: 'TABULAR',
      rowCount: 250,
      nodeCount: 250,
      edgeCount: 0,
      depth: 0,
      numericColumns: 5,
      categoricalColumns: 1,
      temporalColumns: 0,
      hasTimeSeries: false,
      hasContinuousValues: true,
      density: 0.6,
      estimatedDensity: 0.6,
      outlierCount: 0,
      cardinalityOfColor: 3,
      hasHighCardinality: false,
      isLargeDataset: false,
      clusterCount: 3,
      columnStats: {},
      correlationMatrix: {
        x: { y: 0.92, z: 0.88 },
      },
      categoryDistribution: {},
      trendDirection: 'flat',
      seasonalityHint: false,
      hasOutliers: false,
      hasHighVariance: true,
      numericSkew: 0.4,
      topCategory: null,
    },
    spectralFacts: null,
    requirements: createDefaultRequirements('compare-clusters'),
    expectedFamily: 'CLUSTER',
    minConfidence: 0.55,
  },
  {
    name: 'anomalous-outliers',
    description: 'Continuous distribution with extreme heavy-tail skew and outliers',
    facts: {
      topology: 'TABULAR',
      rowCount: 500,
      nodeCount: 500,
      edgeCount: 0,
      depth: 0,
      numericColumns: 2,
      categoricalColumns: 0,
      temporalColumns: 0,
      hasTimeSeries: false,
      hasContinuousValues: true,
      density: 0.2,
      estimatedDensity: 0.2,
      outlierCount: 25,
      cardinalityOfColor: 0,
      hasHighCardinality: false,
      isLargeDataset: true,
      clusterCount: 1,
      columnStats: {},
      correlationMatrix: {},
      categoryDistribution: {},
      trendDirection: 'flat',
      seasonalityHint: false,
      hasOutliers: true,
      hasHighVariance: true,
      numericSkew: 2.8,
      topCategory: null,
    },
    spectralFacts: null,
    requirements: createDefaultRequirements('identify-outliers'),
    expectedFamily: 'DISTRIBUTION',
    minConfidence: 0.55,
  },
  {
    name: 'social-network',
    description: 'Relational graph with high edge connectivity and cycles',
    facts: {
      topology: 'GRAPH',
      rowCount: 80,
      nodeCount: 80,
      edgeCount: 220,
      depth: 0,
      numericColumns: 1,
      categoricalColumns: 1,
      temporalColumns: 0,
      hasTimeSeries: false,
      hasContinuousValues: false,
      density: 0.7,
      estimatedDensity: 0.7,
      outlierCount: 0,
      cardinalityOfColor: 3,
      hasHighCardinality: false,
      isLargeDataset: false,
      clusterCount: 3,
      columnStats: {},
      correlationMatrix: {},
      categoryDistribution: {},
      trendDirection: 'flat',
      seasonalityHint: false,
      hasOutliers: false,
      hasHighVariance: false,
      numericSkew: 0,
      topCategory: null,
    },
    spectralFacts: null,
    requirements: createDefaultRequirements('relationship-discovery'),
    expectedFamily: 'GRAPH',
    minConfidence: 0.55,
  },
  {
    name: 'time-series-trend',
    description: 'Ordered chronological stream with upward metric drift',
    facts: {
      topology: 'TIME_SERIES',
      rowCount: 100,
      nodeCount: 100,
      edgeCount: 0,
      depth: 1,
      numericColumns: 2,
      categoricalColumns: 0,
      temporalColumns: 1,
      hasTimeSeries: true,
      hasContinuousValues: true,
      density: 0.1,
      estimatedDensity: 0.1,
      outlierCount: 0,
      cardinalityOfColor: 0,
      hasHighCardinality: false,
      isLargeDataset: false,
      clusterCount: 1,
      columnStats: {},
      correlationMatrix: {},
      categoryDistribution: {},
      trendDirection: 'up',
      seasonalityHint: false,
      hasOutliers: false,
      hasHighVariance: false,
      numericSkew: 0,
      topCategory: null,
    },
    spectralFacts: null,
    requirements: createDefaultRequirements('temporal-trend'),
    expectedFamily: 'TEMPORAL',
    minConfidence: 0.55,
  },
  {
    name: 'organizational-hierarchy',
    description: 'Deep nested tree hierarchy with root, departments, and teams',
    facts: {
      topology: 'HIERARCHY',
      rowCount: 60,
      nodeCount: 60,
      edgeCount: 59,
      depth: 4,
      numericColumns: 1,
      categoricalColumns: 2,
      temporalColumns: 0,
      hasTimeSeries: false,
      hasContinuousValues: true,
      density: 0.2,
      estimatedDensity: 0.2,
      outlierCount: 0,
      cardinalityOfColor: 4,
      hasHighCardinality: false,
      isLargeDataset: false,
      clusterCount: 4,
      columnStats: {},
      correlationMatrix: {},
      categoryDistribution: {},
      trendDirection: 'flat',
      seasonalityHint: false,
      hasOutliers: false,
      hasHighVariance: false,
      numericSkew: 0,
      topCategory: null,
    },
    spectralFacts: null,
    requirements: createDefaultRequirements('trace-lineage'),
    expectedFamily: 'HIERARCHICAL',
    minConfidence: 0.55,
  },
  {
    name: 'wind-vector-field',
    description: '3D spatial streamline vector field simulation',
    facts: {
      topology: 'VECTOR_FIELD',
      rowCount: 150,
      nodeCount: 150,
      edgeCount: 0,
      depth: 0,
      numericColumns: 6,
      categoricalColumns: 0,
      temporalColumns: 0,
      hasTimeSeries: false,
      hasContinuousValues: true,
      density: 0.5,
      estimatedDensity: 0.5,
      outlierCount: 0,
      cardinalityOfColor: 0,
      hasHighCardinality: false,
      isLargeDataset: false,
      clusterCount: 1,
      columnStats: {},
      correlationMatrix: {},
      categoryDistribution: {},
      trendDirection: 'flat',
      seasonalityHint: false,
      hasOutliers: false,
      hasHighVariance: false,
      numericSkew: 0,
      topCategory: null,
    },
    spectralFacts: null,
    requirements: createDefaultRequirements('individual-inspection'),
    expectedFamily: 'FIELD',
    minConfidence: 0.55,
  },
];
